[package]
name = "rustradio"
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ThomasHabets/rustradio"
description = "Software defined radio library"
include = ["/src/*.rs", "/src/bin/*.rs", ".gitignore", "/extra/precommit", "README.md", "/examples", "/Cargo.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
log = "0.4.20"
num = "0.4.1"
rustfft = "6.1.0"
tempfile = "3.8.0"

[lib]
name = "rustradio"
path = "src/lib.rs"

[[bin]]
name = "bleh"
path = "src/bin/bleh.rs"

[profile.release]
overflow-checks = true
