[package]
name = "rustradio"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Software defined radio library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
log = "0.4.20"
num = "0.4.1"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "bleh"
path = "src/bin/bleh.rs"
